#############################################################################
# Makefile for building: MGAConnect
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sa. Okt 31 08:06:40 2020
# Project:  MGAConnect.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile MGAConnect.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-MGAStringLib \
		sub-MGAWithSQL

MGAStringLib//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) MGAStringLib/ || $(MKDIR) MGAStringLib/ 
	cd MGAStringLib/ && $(QMAKE) /home/tosson/Desktop/MGAWithSQLProject/MGAStringLib/MGAStringLib.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-MGAStringLib-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) MGAStringLib/ || $(MKDIR) MGAStringLib/ 
	cd MGAStringLib/ && $(QMAKE) /home/tosson/Desktop/MGAWithSQLProject/MGAStringLib/MGAStringLib.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-MGAStringLib: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE)
sub-MGAStringLib-make_default-ordered: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) 
sub-MGAStringLib-make_default: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) 
sub-MGAStringLib-make_first-ordered: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) first
sub-MGAStringLib-make_first: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) first
sub-MGAStringLib-all-ordered: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) all
sub-MGAStringLib-all: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) all
sub-MGAStringLib-clean-ordered: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) clean
sub-MGAStringLib-clean: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) clean
sub-MGAStringLib-distclean-ordered: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-MGAStringLib-distclean: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-MGAStringLib-install_subtargets-ordered: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) install
sub-MGAStringLib-install_subtargets: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) install
sub-MGAStringLib-uninstall_subtargets-ordered: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-MGAStringLib-uninstall_subtargets: MGAStringLib//$(MAKEFILE) FORCE
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) uninstall
MGAWithSQL//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) MGAWithSQL/ || $(MKDIR) MGAWithSQL/ 
	cd MGAWithSQL/ && $(QMAKE) /home/tosson/Desktop/MGAWithSQLProject/MGAWithSQL/MGAWithSQL.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-MGAWithSQL-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) MGAWithSQL/ || $(MKDIR) MGAWithSQL/ 
	cd MGAWithSQL/ && $(QMAKE) /home/tosson/Desktop/MGAWithSQLProject/MGAWithSQL/MGAWithSQL.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-MGAWithSQL: MGAWithSQL//$(MAKEFILE) FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE)
sub-MGAWithSQL-make_default-ordered: MGAWithSQL//$(MAKEFILE) sub-MGAStringLib-make_default-ordered  FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) 
sub-MGAWithSQL-make_default: MGAWithSQL//$(MAKEFILE) FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) 
sub-MGAWithSQL-make_first-ordered: MGAWithSQL//$(MAKEFILE) sub-MGAStringLib-make_first-ordered  FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) first
sub-MGAWithSQL-make_first: MGAWithSQL//$(MAKEFILE) FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) first
sub-MGAWithSQL-all-ordered: MGAWithSQL//$(MAKEFILE) sub-MGAStringLib-all-ordered  FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) all
sub-MGAWithSQL-all: MGAWithSQL//$(MAKEFILE) FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) all
sub-MGAWithSQL-clean-ordered: MGAWithSQL//$(MAKEFILE) sub-MGAStringLib-clean-ordered  FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) clean
sub-MGAWithSQL-clean: MGAWithSQL//$(MAKEFILE) FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) clean
sub-MGAWithSQL-distclean-ordered: MGAWithSQL//$(MAKEFILE) sub-MGAStringLib-distclean-ordered  FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) distclean
sub-MGAWithSQL-distclean: MGAWithSQL//$(MAKEFILE) FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) distclean
sub-MGAWithSQL-install_subtargets-ordered: MGAWithSQL//$(MAKEFILE) sub-MGAStringLib-install_subtargets-ordered  FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) install
sub-MGAWithSQL-install_subtargets: MGAWithSQL//$(MAKEFILE) FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) install
sub-MGAWithSQL-uninstall_subtargets-ordered: MGAWithSQL//$(MAKEFILE) sub-MGAStringLib-uninstall_subtargets-ordered  FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-MGAWithSQL-uninstall_subtargets: MGAWithSQL//$(MAKEFILE) FORCE
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: MGAConnect.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile MGAConnect.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile MGAConnect.pro

qmake_all: sub-MGAStringLib-qmake_all sub-MGAWithSQL-qmake_all FORCE

make_default: sub-MGAStringLib-make_default-ordered sub-MGAWithSQL-make_default-ordered FORCE
make_first: sub-MGAStringLib-make_first-ordered sub-MGAWithSQL-make_first-ordered FORCE
all: sub-MGAStringLib-all-ordered sub-MGAWithSQL-all-ordered FORCE
clean: sub-MGAStringLib-clean-ordered sub-MGAWithSQL-clean-ordered FORCE
distclean: sub-MGAStringLib-distclean-ordered sub-MGAWithSQL-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-MGAStringLib-install_subtargets-ordered sub-MGAWithSQL-install_subtargets-ordered FORCE
uninstall_subtargets: sub-MGAStringLib-uninstall_subtargets-ordered sub-MGAWithSQL-uninstall_subtargets-ordered FORCE

sub-MGAStringLib-check_ordered: MGAStringLib/$(MAKEFILE)
	cd MGAStringLib/ && $(MAKE) -f $(MAKEFILE) check
sub-MGAWithSQL-check_ordered: MGAWithSQL/$(MAKEFILE) sub-MGAStringLib-check_ordered 
	cd MGAWithSQL/ && $(MAKE) -f $(MAKEFILE) check
check: sub-MGAStringLib-check_ordered sub-MGAWithSQL-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

