#ifndef MGACOMMONACTIONSRESCOURCES_H
#define MGACOMMONACTIONSRESCOURCES_H

#define SERVER_MENU_DISCONNECT_ACTION_TXT       "Disconnect"
#define SERVER_MENU_CONNECT_ACTION_TXT          "Connect"
#define SERVER_MENU_TEST_CON_ACTION_TXT         "Test connection"
#define SERVER_MENU_RECONNECT_ACTION_TXT        "Reconnect"
#define SERVER_MENU_SETTINGS_ACTION_TXT         "Server settings"
#endif // MGACOMMONACTIONSRESCOURCES_H
